[2025-02-08T19:02:42.592+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:02:42.607+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-08T19:02:42.616+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-08T19:02:42.617+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:02:42.632+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-28 00:00:00+00:00
[2025-02-08T19:02:42.642+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1605) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:02:42.643+0000] {standard_task_runner.py:72} INFO - Started process 1619 to run task
[2025-02-08T19:02:42.642+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmptmclahyr']
[2025-02-08T19:02:42.645+0000] {standard_task_runner.py:105} INFO - Job 262: Subtask generate_customer_dim_data
[2025-02-08T19:02:42.690+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:02:42.784+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2025-02-08T19:02:42.785+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:02:42.808+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:02:42.809+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:02:42.819+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:02:42.820+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20250208T190242, end_date=20250208T190242
[2025-02-08T19:02:43.019+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:02:43.057+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:02:43.066+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:40:23.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:40:23.058+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-08T20:40:23.069+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-08T20:40:23.070+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:40:23.119+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-28 00:00:00+00:00
[2025-02-08T20:40:23.131+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:40:23.133+0000] {standard_task_runner.py:72} INFO - Started process 1271 to run task
[2025-02-08T20:40:23.150+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmp281t3nyn']
[2025-02-08T20:40:23.167+0000] {standard_task_runner.py:105} INFO - Job 160: Subtask generate_customer_dim_data
[2025-02-08T20:40:23.301+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:40:23.424+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2025-02-08T20:40:23.427+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:40:23.450+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:40:23.451+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:40:23.494+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:40:23.494+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20250208T204023, end_date=20250208T204023
[2025-02-08T20:40:23.558+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:40:23.581+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:12.342+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:12.363+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-08T20:43:12.374+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-08T20:43:12.376+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:12.393+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-28 00:00:00+00:00
[2025-02-08T20:43:12.403+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=601) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:12.404+0000] {standard_task_runner.py:72} INFO - Started process 620 to run task
[2025-02-08T20:43:12.403+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpapqnz379']
[2025-02-08T20:43:12.405+0000] {standard_task_runner.py:105} INFO - Job 457: Subtask generate_customer_dim_data
[2025-02-08T20:43:12.454+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-28T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:12.536+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2025-02-08T20:43:12.537+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:12.553+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:12.553+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:12.561+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:12.562+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20250208T204312, end_date=20250208T204312
[2025-02-08T20:43:12.579+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:12.593+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:43:12.595+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
