[2025-02-08T19:03:14.831+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:03:14.851+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-02-08T19:03:14.860+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-02-08T19:03:14.861+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:03:14.876+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-16 00:00:00+00:00
[2025-02-08T19:03:14.889+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2021) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:03:14.890+0000] {standard_task_runner.py:72} INFO - Started process 2046 to run task
[2025-02-08T19:03:14.891+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-16T00:00:00+00:00', '--job-id', '359', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpfw6l6xok']
[2025-02-08T19:03:14.894+0000] {standard_task_runner.py:105} INFO - Job 359: Subtask generate_customer_dim_data
[2025-02-08T19:03:14.955+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:03:15.049+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-16T00:00:00+00:00'
[2025-02-08T19:03:15.054+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:03:15.078+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:03:15.078+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:03:15.090+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:03:15.091+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-16T00:00:00+00:00, execution_date=20250116T000000, start_date=20250208T190314, end_date=20250208T190315
[2025-02-08T19:03:15.120+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:03:15.156+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:03:15.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:41:01.829+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:41:01.859+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-02-08T20:41:01.879+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-02-08T20:41:01.880+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:41:01.921+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-16 00:00:00+00:00
[2025-02-08T20:41:01.940+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1860) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:41:01.942+0000] {standard_task_runner.py:72} INFO - Started process 1899 to run task
[2025-02-08T20:41:01.941+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-16T00:00:00+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpplnfsl0x']
[2025-02-08T20:41:01.946+0000] {standard_task_runner.py:105} INFO - Job 307: Subtask generate_customer_dim_data
[2025-02-08T20:41:02.049+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:41:02.215+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-16T00:00:00+00:00'
[2025-02-08T20:41:02.218+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:41:02.256+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:41:02.256+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:41:02.272+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:41:02.272+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-16T00:00:00+00:00, execution_date=20250116T000000, start_date=20250208T204101, end_date=20250208T204102
[2025-02-08T20:41:02.324+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:41:02.344+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:41:02.349+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:39.949+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:39.966+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-02-08T20:43:39.974+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-02-08T20:43:39.975+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:39.989+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-16 00:00:00+00:00
[2025-02-08T20:43:39.999+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=828) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:40.000+0000] {standard_task_runner.py:72} INFO - Started process 844 to run task
[2025-02-08T20:43:39.998+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-16T00:00:00+00:00', '--job-id', '506', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpe658_nz9']
[2025-02-08T20:43:40.001+0000] {standard_task_runner.py:105} INFO - Job 506: Subtask generate_customer_dim_data
[2025-02-08T20:43:40.042+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-16T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:40.117+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-16T00:00:00+00:00'
[2025-02-08T20:43:40.118+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:40.135+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:40.136+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:40.144+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:40.144+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-16T00:00:00+00:00, execution_date=20250116T000000, start_date=20250208T204339, end_date=20250208T204340
[2025-02-08T20:43:40.175+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:40.190+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:43:40.193+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
