[2025-02-09T20:29:17.248+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T20:29:17.264+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-02-09T02:04:10+00:00 [queued]>
[2025-02-09T20:29:17.274+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-02-09T02:04:10+00:00 [queued]>
[2025-02-09T20:29:17.274+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-09T20:29:17.312+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-02-09 02:04:10+00:00
[2025-02-09T20:29:17.321+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=846) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T20:29:17.322+0000] {standard_task_runner.py:72} INFO - Started process 868 to run task
[2025-02-09T20:29:17.321+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-02-09T02:04:10+00:00', '--job-id', '1700', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmplabhisry']
[2025-02-09T20:29:17.324+0000] {standard_task_runner.py:105} INFO - Job 1700: Subtask generate_account_dim_data
[2025-02-09T20:29:17.362+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-02-09T02:04:10+00:00 [running]> on host eb23718e9774
[2025-02-09T20:29:17.435+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T02:04:10+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-09T02:04:10+00:00'
[2025-02-09T20:29:17.436+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T20:29:17.452+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-09T20:29:17.453+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-09T20:29:17.460+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T20:29:17.461+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-02-09T02:04:10+00:00, execution_date=20250209T020410, start_date=20250209T202917, end_date=20250209T202917
[2025-02-09T20:29:17.496+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T20:29:17.512+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T20:29:17.515+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
