[2025-02-08T19:02:36.717+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:02:36.750+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-02-08T19:02:36.768+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-02-08T19:02:36.769+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:02:36.781+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-19 00:00:00+00:00
[2025-02-08T19:02:36.794+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1530) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:02:36.797+0000] {standard_task_runner.py:72} INFO - Started process 1552 to run task
[2025-02-08T19:02:36.801+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-19T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpe_h612t2']
[2025-02-08T19:02:36.804+0000] {standard_task_runner.py:105} INFO - Job 243: Subtask generate_customer_dim_data
[2025-02-08T19:02:36.874+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:02:36.989+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T00:00:00+00:00'
[2025-02-08T19:02:36.991+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:02:37.020+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:02:37.020+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:02:37.029+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:02:37.030+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-19T00:00:00+00:00, execution_date=20241119T000000, start_date=20250208T190236, end_date=20250208T190237
[2025-02-08T19:02:37.057+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:02:37.076+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:02:37.081+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:40:15.011+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:40:15.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-02-08T20:40:15.047+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-02-08T20:40:15.050+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:40:15.065+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-19 00:00:00+00:00
[2025-02-08T20:40:15.077+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1121) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:40:15.078+0000] {standard_task_runner.py:72} INFO - Started process 1152 to run task
[2025-02-08T20:40:15.077+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-19T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmp4x572cou']
[2025-02-08T20:40:15.080+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask generate_customer_dim_data
[2025-02-08T20:40:15.138+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:40:15.289+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T00:00:00+00:00'
[2025-02-08T20:40:15.294+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:40:15.326+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:40:15.336+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:40:15.347+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:40:15.349+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-19T00:00:00+00:00, execution_date=20241119T000000, start_date=20250208T204015, end_date=20250208T204015
[2025-02-08T20:40:15.416+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:40:15.430+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:05.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:05.860+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-02-08T20:43:05.869+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2025-02-08T20:43:05.869+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:05.879+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-19 00:00:00+00:00
[2025-02-08T20:43:05.888+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=561) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:05.889+0000] {standard_task_runner.py:72} INFO - Started process 573 to run task
[2025-02-08T20:43:05.889+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-19T00:00:00+00:00', '--job-id', '448', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmp5sh82ypb']
[2025-02-08T20:43:05.891+0000] {standard_task_runner.py:105} INFO - Job 448: Subtask generate_customer_dim_data
[2025-02-08T20:43:05.931+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-19T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:05.999+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T00:00:00+00:00'
[2025-02-08T20:43:06.000+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:06.016+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:06.017+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:06.024+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:06.025+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-19T00:00:00+00:00, execution_date=20241119T000000, start_date=20250208T204305, end_date=20250208T204306
[2025-02-08T20:43:06.063+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:06.076+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:43:06.078+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
