[2025-02-08T19:02:30.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:02:30.603+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2025-02-08T19:02:30.613+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2025-02-08T19:02:30.613+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:02:30.627+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-16 00:00:00+00:00
[2025-02-08T19:02:30.636+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1491) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:02:30.637+0000] {standard_task_runner.py:72} INFO - Started process 1509 to run task
[2025-02-08T19:02:30.636+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-16T00:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmp5vkod5ft']
[2025-02-08T19:02:30.638+0000] {standard_task_runner.py:105} INFO - Job 236: Subtask generate_customer_dim_data
[2025-02-08T19:02:30.696+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:02:30.783+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-16T00:00:00+00:00'
[2025-02-08T19:02:30.784+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:02:30.804+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:02:30.805+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:02:30.814+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:02:30.814+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-16T00:00:00+00:00, execution_date=20241116T000000, start_date=20250208T190230, end_date=20250208T190230
[2025-02-08T19:02:30.853+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:02:30.868+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:02:30.870+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:40:14.106+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:40:14.125+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2025-02-08T20:40:14.140+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2025-02-08T20:40:14.140+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:40:14.265+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-16 00:00:00+00:00
[2025-02-08T20:40:14.277+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1104) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:40:14.279+0000] {standard_task_runner.py:72} INFO - Started process 1124 to run task
[2025-02-08T20:40:14.281+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-16T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpjutnns0t']
[2025-02-08T20:40:14.283+0000] {standard_task_runner.py:105} INFO - Job 125: Subtask generate_customer_dim_data
[2025-02-08T20:40:14.359+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:40:14.466+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-16T00:00:00+00:00'
[2025-02-08T20:40:14.469+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:40:14.491+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:40:14.492+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:40:14.505+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:40:14.506+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-16T00:00:00+00:00, execution_date=20241116T000000, start_date=20250208T204014, end_date=20250208T204014
[2025-02-08T20:40:14.542+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:40:14.552+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:05.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:05.454+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2025-02-08T20:43:05.464+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2025-02-08T20:43:05.465+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:05.522+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-16 00:00:00+00:00
[2025-02-08T20:43:05.532+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=547) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:05.533+0000] {standard_task_runner.py:72} INFO - Started process 567 to run task
[2025-02-08T20:43:05.532+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-16T00:00:00+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpxfsbem_d']
[2025-02-08T20:43:05.535+0000] {standard_task_runner.py:105} INFO - Job 445: Subtask generate_customer_dim_data
[2025-02-08T20:43:05.572+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-16T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:05.646+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-16T00:00:00+00:00'
[2025-02-08T20:43:05.647+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:05.666+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:05.666+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:05.674+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:05.674+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-16T00:00:00+00:00, execution_date=20241116T000000, start_date=20250208T204305, end_date=20250208T204305
[2025-02-08T20:43:05.708+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:05.723+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:43:05.726+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
