[2025-02-08T19:01:18.848+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:01:18.863+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-08T19:01:18.874+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-08T19:01:18.875+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:01:18.926+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-01-31 00:00:00+00:00
[2025-02-08T19:01:18.935+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1093) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:01:18.936+0000] {standard_task_runner.py:72} INFO - Started process 1109 to run task
[2025-02-08T19:01:18.935+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpkc6pgx71']
[2025-02-08T19:01:18.938+0000] {standard_task_runner.py:105} INFO - Job 147: Subtask generate_account_dim_data
[2025-02-08T19:01:18.980+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-31T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:01:19.060+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-02-08T19:01:19.061+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:01:19.082+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T19:01:19.083+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:01:19.092+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:01:19.093+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250208T190118, end_date=20250208T190119
[2025-02-08T19:01:19.193+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:01:19.210+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:01:19.212+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:42:41.157+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:42:41.170+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-08T20:42:41.180+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-08T20:42:41.181+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:42:41.192+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-01-31 00:00:00+00:00
[2025-02-08T20:42:41.201+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpt0nfiu2u']
[2025-02-08T20:42:41.204+0000] {standard_task_runner.py:105} INFO - Job 392: Subtask generate_account_dim_data
[2025-02-08T20:42:41.204+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:42:41.204+0000] {standard_task_runner.py:72} INFO - Started process 330 to run task
[2025-02-08T20:42:41.245+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-31T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:42:41.320+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-02-08T20:42:41.321+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:42:41.343+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T20:42:41.343+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:42:41.352+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:42:41.352+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250208T204241, end_date=20250208T204241
[2025-02-08T20:42:41.378+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:42:41.393+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:42:41.396+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
