[2025-02-08T19:02:43.194+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:02:43.215+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [queued]>
[2025-02-08T19:02:43.228+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [queued]>
[2025-02-08T19:02:43.228+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:02:43.255+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-29 00:00:00+00:00
[2025-02-08T19:02:43.267+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1609) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:02:43.268+0000] {standard_task_runner.py:72} INFO - Started process 1639 to run task
[2025-02-08T19:02:43.267+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-29T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpbswkb58w']
[2025-02-08T19:02:43.270+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask generate_customer_dim_data
[2025-02-08T19:02:43.347+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:02:43.447+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-29T00:00:00+00:00'
[2025-02-08T19:02:43.458+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:02:43.482+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:02:43.483+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:02:43.494+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:02:43.494+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-29T00:00:00+00:00, execution_date=20241129T000000, start_date=20250208T190243, end_date=20250208T190243
[2025-02-08T19:02:43.552+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:02:43.571+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:02:43.575+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:40:23.366+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:40:23.394+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [queued]>
[2025-02-08T20:40:23.405+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [queued]>
[2025-02-08T20:40:23.407+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:40:23.424+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-29 00:00:00+00:00
[2025-02-08T20:40:23.439+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:40:23.440+0000] {standard_task_runner.py:72} INFO - Started process 1279 to run task
[2025-02-08T20:40:23.461+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-29T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmp61lm_f8z']
[2025-02-08T20:40:23.465+0000] {standard_task_runner.py:105} INFO - Job 163: Subtask generate_customer_dim_data
[2025-02-08T20:40:23.584+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:40:23.713+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-29T00:00:00+00:00'
[2025-02-08T20:40:23.717+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:40:23.744+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:40:23.746+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:40:23.767+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:40:23.768+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-29T00:00:00+00:00, execution_date=20241129T000000, start_date=20250208T204023, end_date=20250208T204023
[2025-02-08T20:40:23.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:40:23.853+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:40:23.855+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:12.520+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:12.535+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [queued]>
[2025-02-08T20:43:12.542+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [queued]>
[2025-02-08T20:43:12.543+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:12.554+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-11-29 00:00:00+00:00
[2025-02-08T20:43:12.563+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=607) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:12.564+0000] {standard_task_runner.py:72} INFO - Started process 623 to run task
[2025-02-08T20:43:12.563+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-11-29T00:00:00+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpipcciz3j']
[2025-02-08T20:43:12.565+0000] {standard_task_runner.py:105} INFO - Job 458: Subtask generate_customer_dim_data
[2025-02-08T20:43:12.605+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-11-29T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:12.682+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-29T00:00:00+00:00'
[2025-02-08T20:43:12.683+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:12.700+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:12.701+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:12.708+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:12.709+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-11-29T00:00:00+00:00, execution_date=20241129T000000, start_date=20250208T204312, end_date=20250208T204312
[2025-02-08T20:43:12.738+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:12.752+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:43:12.754+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
